mutation createEmployee(
  $name: String!
  $city: String!
  $department: String!
  $gender: String!
) @auth(level: USER) {
  employee_insert(
    data: { name: $name, city: $city, department: $department, gender: $gender }
  )
}

mutation updateEmployee(
  $id: UUID!
  $name: String!
  $city: String!
  $department: String!
  $gender: String!
) @auth(level: USER) {
  employee_update(
    id: $id
    data: { name: $name, city: $city, department: $department, gender: $gender }
  )
}

mutation deleteEmployee($id: UUID!) @auth(level: USER) {
  employee_delete(id: $id)
}
