query ListCities @auth(level: PUBLIC) {
  cities {
    id
    cityName
  }
}

query ListEmployees @auth(level: PUBLIC) {
  employees(orderBy: [{ name: ASC }]) {
    id
    name
    gender
    department
    city
  }
}

query ListEmployeeByID($uid: UUID) @auth(level: PUBLIC) {
  employees(where: { id: { eq: $uid } }) {
    id
    name
    gender
    department
    city
  }
}
