query ListCities {
  cities {
    id
    cityName
  }
}

query ListEmployees {
  employees(orderBy: [{ name: ASC }]) {
    id
    name
    gender
    department
    city
  }
}

query ListEmployeeByID($uid: UUID) {
  employees(where: { id: { eq: $uid } }) {
    id
    name
    gender
    department
    city
  }
}
