# This is a file for you to write an un-named mutation.
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(
    data: {
      uid: "user3" # String
      address: "Goa" # String
      name: "qwerty" # String
    }
  )
}
